#!/bin/bash

################################################################################
# WARNING: DO NOT EDIT THIS FILE MANUALLY!
#
# This file is automatically downloaded and managed by the egg installer.
# Any manual changes you make will be overwritten on the next update.
#
# To customize server settings, use the egg configuration variables in your
# Pelican panel instead.
################################################################################

DOWNLOADER="./hytale-downloader-linux-amd64"

# Run automatic update if enabled
if [ "${AUTOMATIC_UPDATE}" = "1" ]; then
    # Check if the downloader exists
    if [ ! -f "$DOWNLOADER" ]; then
        echo "Error: Hytale downloader not found!"
        echo "Please run the installation script first."
        exit 1
    fi

    # Check if the downloader is executable
    if [ ! -x "$DOWNLOADER" ]; then
        echo "Setting executable permissions..."
        chmod +x "$DOWNLOADER"
    fi

    echo "Starting Hytale downloader..."
    $DOWNLOADER -check-update
    $DOWNLOADER
fi

echo "Starting Hytale server..."

# Build the Java command
JAVA_CMD="java"

# Add AOT cache if enabled
if [ "${LEVERAGE_AHEAD_OF_TIME_CACHE}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} -XX:AOTCache=HytaleServer.aot"
fi

# Add max memory if set and greater than 0
if [ -n "${SERVER_MEMORY}" ] && [ "${SERVER_MEMORY}" -gt 0 ] 2>/dev/null; then
    JAVA_CMD="${JAVA_CMD} -Xms${SERVER_MEMORY}M -Xmx${SERVER_MEMORY}M"
fi

# Add JVM arguments if set
if [ -n "${JVM_ARGS}" ]; then
    JAVA_CMD="${JAVA_CMD} ${JVM_ARGS}"
fi

JAVA_CMD="${JAVA_CMD} -jar HytaleServer.jar"

# Add assets parameter if set and ends with .zip
if [ -n "${ASSET_PACK}" ] && [[ "${ASSET_PACK}" == *.zip ]]; then
    JAVA_CMD="${JAVA_CMD} --assets ${ASSET_PACK}"
fi

# Add accept-early-plugins flag if variable is set
if [ -n "${ACCEPT_EARLY_PLUGINS}" ]; then
    JAVA_CMD="${JAVA_CMD} --accept-early-plugins"
fi

JAVA_CMD="${JAVA_CMD} --auth-mode ${AUTH_MODE}"

# Add allow-op flag if variable is set
if [ -n "${ALLOW_OP}" ]; then
    JAVA_CMD="${JAVA_CMD} --allow-op"
fi

# Add disable-sentry flag if enabled
if [ "${DISABLE_SENTRY}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} --disable-sentry"
fi

# Add backup parameters if enabled
if [ "${ENABLE_BACKUPS}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} --backup --backup-dir ${BACKUP_DIRECTORY} --backup-frequency ${BACKUP_FREQUENCY}"
fi

# Add bind address
JAVA_CMD="${JAVA_CMD} --bind 0.0.0.0:${SERVER_PORT}"

# Execute the command
eval $JAVA_CMD
